#install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
#devtools::install_github('IRkernel/IRkernel')
#IRkernel::installspec()
install.packages("rodbc")
install.packages("getopt")
install.packages("tools")
install.packages("ggmap")
install.packages("compiler")
install.packages("arules")
install.packages("arulesViz")
install.packages("xgboost")

