try(install.packages('devtools'), silent=TRUE)
try(install.packages("RODBC"), silent=TRUE)
try(install.packages("getopt"), silent=TRUE)
try(install.packages("tools"), silent=TRUE)
try(install.packages("ggmap"), silent=TRUE)
try(install.packages("compiler"), silent=TRUE)
try(install.packages("arules"), silent=TRUE)
try(install.packages("arulesViz"), silent=TRUE)
try(install.packages("xgboost"), silent=TRUE)
try(install.packages("scatterplot3d"), silent=TRUE)
try(install.packages("dendextend"), silent=TRUE)
try(install.packages("r-plotly"), silent=TRUE)
#install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec()
